In [99]:
import pandas as pd
from uszipcode import ZipcodeSearchEngine
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

from datetime import datetime
import numpy as np

In [100]:
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:

# Note that you'll have to paste our API key here. I haven't included it since this will go to the Github repo
client = Socrata("data.lacity.org", "LLaYxNjJnTyIyES7N63sJAUDv")


#Only getting the first 1000 rows to ease computational requirements but when we have all of our codes written
#we should grab the full dataset.
result_list = client.get("7fvc-faax", limit=1000)

# Convert to pandas DataFrame
crime_df = pd.DataFrame.from_records(result_list)
crime_df.head()

,area_id,area_name,crm_cd,crm_cd_1,crm_cd_2,crm_cd_3,crm_cd_4,crm_cd_desc,cross_street,date_occ,date_rptd,dr_no,location,location_1,mocodes,premis_cd,premis_desc,rpt_dist_no,status,status_desc,time_occ,vict_age,vict_descent,vict_sex,weapon_desc,weapon_used_cd
0,01,Central,740,740,NaN,NaN,NaN,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",NaN,2017-11-02T00:00:00.000,2017-11-02T00:00:00.000,170101261,1800 S BROADWAY,"{'type': 'Point', 'coordinates': [-118.2647, 3...",0329 2004,203,OTHER BUSINESS,0195,IC,Invest Cont,2130,58,H,M,NaN,NaN
1,01,Central,888,888,NaN,NaN,NaN,TRESPASSING,ALAMEDA ST,2017-10-30T00:00:00.000,2017-10-30T00:00:00.000,170128267,LOS ANGELES ST,"{'type': 'Point', 'coordinates': [-118.2318, 3...",0910 2028 1501 2004,135,MTA PROPERTY OR PARKING LOT,0119,IC,Invest Cont,2230,48,H,M,NaN,NaN
2,20,Olympic,740,740,NaN,NaN,NaN,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",NaN,2018-06-30T00:00:00.000,2018-06-30T00:00:00.000,182013514,800 S KENMORE AV,"{'type': 'Point', 'coordinates': [-118.2981, 3...",0329,122,"VEHICLE, PASSENGER/TRUCK",2045,IC,Invest Cont,0205,32,H,M,NaN,NaN
3,01,Central,330,330,NaN,NaN,NaN,BURGLARY FROM VEHICLE,NaN,2017-11-01T00:00:00.000,2017-11-01T00:00:00.000,170128444,300 S SANTA FE AV,"{'type': 'Point', 'coordinates': [-118.2326, 3...",1609 1307 0358 0344,101,STREET,0139,IC,Invest Cont,1730,20,H,M,NaN,NaN
4,01,Central,330,330,NaN,NaN,NaN,BURGLARY FROM VEHICLE,SAN PEDRO ST,2017-11-01T00:00:00.000,2017-11-01T00:00:00.000,170128445,3RD ST,"{'type': 'Point', 'coordinates': [-118.2411, 3...",0344 1609 1307 0358,101,STREET,0138,IC,Invest Cont,2200,22,H,F,NaN,NaN

In [101]:
# Converting "date_occ" row to a datetime object
crime_df["date_occ"]=pd.to_datetime(crime_df["date_occ"])

#IGNORE THIS
#Strip month and year from date
#converted_dates = []
#for date in crime_df["date_occ"]:
    #converted_time = datetime.strptime(date, "Y%-%m-%d")
    #converted_dates.append(converted_time)

#Create new columns in Crime dataframe for Month and Year
crime_df["Month"] = [date.month for date in crime_df["date_occ"]]
crime_df["Year"] = [date.year for date in crime_df["date_occ"]]
crime_df.head()

,area_id,area_name,crm_cd,crm_cd_1,crm_cd_2,crm_cd_3,crm_cd_4,crm_cd_desc,cross_street,date_occ,date_rptd,dr_no,location,location_1,mocodes,premis_cd,premis_desc,rpt_dist_no,status,status_desc,time_occ,vict_age,vict_descent,vict_sex,weapon_desc,weapon_used_cd,Month,Year
0,01,Central,740,740,NaN,NaN,NaN,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",NaN,2017-11-02,2017-11-02T00:00:00.000,170101261,1800 S BROADWAY,"{'type': 'Point', 'coordinates': [-118.2647, 3...",0329 2004,203,OTHER BUSINESS,0195,IC,Invest Cont,2130,58,H,M,NaN,NaN,11,2017
1,01,Central,888,888,NaN,NaN,NaN,TRESPASSING,ALAMEDA ST,2017-10-30,2017-10-30T00:00:00.000,170128267,LOS ANGELES ST,"{'type': 'Point', 'coordinates': [-118.2318, 3...",0910 2028 1501 2004,135,MTA PROPERTY OR PARKING LOT,0119,IC,Invest Cont,2230,48,H,M,NaN,NaN,10,2017
2,20,Olympic,740,740,NaN,NaN,NaN,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",NaN,2018-06-30,2018-06-30T00:00:00.000,182013514,800 S KENMORE AV,"{'type': 'Point', 'coordinates': [-118.2981, 3...",0329,122,"VEHICLE, PASSENGER/TRUCK",2045,IC,Invest Cont,0205,32,H,M,NaN,NaN,6,2018
3,01,Central,330,330,NaN,NaN,NaN,BURGLARY FROM VEHICLE,NaN,2017-11-01,2017-11-01T00:00:00.000,170128444,300 S SANTA FE AV,"{'type': 'Point', 'coordinates': [-118.2326, 3...",1609 1307 0358 0344,101,STREET,0139,IC,Invest Cont,1730,20,H,M,NaN,NaN,11,2017
4,01,Central,330,330,NaN,NaN,NaN,BURGLARY FROM VEHICLE,SAN PEDRO ST,2017-11-01,2017-11-01T00:00:00.000,170128445,3RD ST,"{'type': 'Point', 'coordinates': [-118.2411, 3...",0344 1609 1307 0358,101,STREET,0138,IC,Invest Cont,2200,22,H,F,NaN,NaN,11,2017

In [111]:
# Code to look at crime descriptions and their associated crime code
#All the numbers in this data set are stored as objects rather than intergers.
#We may want to convert all numeric columns to numbers but here I'm just converting the crime codes to numbers
crime_df["crm_cd"] = pd.to_numeric(crime_df["crm_cd"])

#Groups by crime description then look at average crime code. This matches 
crime_code = crime_df.groupby("crm_cd_desc")
crime_code = crime_code.mean()
crime_code = crime_code.drop(["Month","Year"], axis=1)
crime_code

                                                    crm_cd
crm_cd_desc
ARSON                                                648.0
ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT       230.0
ATTEMPTED ROBBERY                                    220.0
BATTERY - SIMPLE ASSAULT                             624.0
BATTERY ON A FIREFIGHTER                             622.0
BATTERY POLICE (SIMPLE)                              623.0
BATTERY WITH SEXUAL CONTACT                          860.0
BIKE - STOLEN                                        480.0
BOMB SCARE                                           755.0
BRANDISH WEAPON                                      761.0
BUNCO, GRAND THEFT                                   662.0
BUNCO, PETTY THEFT                                   664.0
BURGLARY                                             310.0
BURGLARY FROM VEHICLE                                330.0
BURGLARY FROM VEHICLE, ATTEMPTED                     410.0
BURGLARY, ATTEMPTED                                  320.0
CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT              627.0
CHILD NEGLECT (SEE 300 W.I.C.)                       237.0
CONTEMPT OF COURT                                    903.0
CRIMINAL THREATS - NO WEAPON DISPLAYED               930.0
CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 Y...   812.0
DEFRAUDING INNKEEPER/THEFT OF SERVICES, $400 & ...   951.0
DISCHARGE FIREARMS/SHOTS FIRED                       753.0
DOCUMENT FORGERY / STOLEN FELONY                     649.0
EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)           668.0
EXTORTION                                            940.0
FALSE POLICE REPORT                                  439.0
INDECENT EXPOSURE                                    850.0
INTIMATE PARTNER - AGGRAVATED ASSAULT                236.0
INTIMATE PARTNER - SIMPLE ASSAULT                    626.0
KIDNAPPING                                           910.0
LETTERS, LEWD                                        956.0
LETTERS, LEWD  -  TELEPHONE CALLS, LEWD              956.0
ORAL COPULATION                                      820.0
OTHER ASSAULT                                        625.0
OTHER MISCELLANEOUS CRIME                            946.0
PANDERING                                            806.0
PICKPOCKET                                           352.0
PURSE SNATCHING                                      351.0
RAPE, FORCIBLE                                       121.0
RESISTING ARREST                                     437.0
ROBBERY                                              210.0
SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/...   810.0
SEXUAL PENETRATION W/FOREIGN OBJECT                  815.0
SHOPLIFTING - PETTY THEFT ($950 & UNDER)             442.0
SHOPLIFTING-GRAND THEFT ($950.01 & OVER)             343.0
SHOTS FIRED AT INHABITED DWELLING                    251.0
SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ...   821.0
THEFT FROM MOTOR VEHICLE - ATTEMPT                   421.0
THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER)     331.0
THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)      420.0
THEFT FROM PERSON - ATTEMPT                          450.0
THEFT OF IDENTITY                                    354.0
THEFT PLAIN - PETTY ($950 & UNDER)                   440.0
THEFT, COIN MACHINE - PETTY ($950 & UNDER)           474.0
THEFT, PERSON                                        350.0
THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIV...   341.0
THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIV...   341.0
THROWING OBJECT AT MOVING VEHICLE                    647.0
TRESPASSING                                          888.0
UNAUTHORIZED COMPUTER ACCESS                         661.0
VANDALISM - FELONY ($400 & OVER, ALL CHURCH VAN...   740.0
VANDALISM - FELONY ($400 & OVER, ALL CHURCH VAN...   740.0
VANDALISM - MISDEAMEANOR ($399 OR UNDER)             745.0
VEHICLE - STOLEN                                     510.0
VIOLATION OF COURT ORDER                             900.0
VIOLATION OF RESTRAINING ORDER                       901.0
VIOLATION OF TEMPORARY RESTRAINING ORDER             902.0